openapi: "3.0.0"
info:
    title: api
    version: "0.0.1"
    description: API のドキュメントです
paths:
    /health:
        get:
            responses:
                '200':
                    description: OK
